version: '3.8'
services:
  db:
    image: postgres:15
    container_name: universidad_db
    environment:
      POSTGRES_DB: universidad
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: clave123
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
